security:
  salt: 2fO0utNp$56
  jwt:
    secret: uZVrPBMsfU
    expirationMinutes: 5

db:
  changelogFile: db/changelog/changelog.xml
  modelSchema: model
  serviceSchema: public
  url: jdbc:postgresql://localhost:5433/habit-tracker?currentSchema=model
  username: habittrackerapp
  password: P@ssw0rd
  driverClassName: org.postgresql.Driver
